# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
resources:
 containers:
   - container: dotnet7
     image: mcr.microsoft.com/dotnet/sdk:7.0

variables:
  buildConfiguration: 'Release'

trigger:
- master

jobs:
- job: 'CI'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UseDotNet@2
      displayName: 'Install SDK'
      inputs:
        version: 7.0.x
        performMultiLevelLookup: true
        includePreviewVersions: true

    - task: Cake@2
      displayName: 'Build and Tests'
      continueOnError: false
      inputs:
        script: 'build.cake'
        target: 'RunTests'
        verbosity: 'Minimal'